log_level                :info
log_location             STDOUT
node_name                'sasi'
client_key               '/Users/sasikumaranandan/Desktop/ATB_Projects/DevOps/chef-repo/.chef/sasi.pem'
validation_client_name   'sasi.pem'
validation_key           '/Users/sasikumaranandan/Desktop/ATB_Projects/DevOps/chef-repo/cookbooks/atb-chef-admin.pem'
chef_server_url          'https://54.211.154.197/organizations/atb'
syntax_check_cache_path  '/Users/sasikumaranandan/Desktop/ATB_Projects/DevOps/chef-repo/.chef/syntax_check_cache'
cookbook_path            '/Users/sasikumaranandan/Desktop/ATB_Projects/DevOps/chef-repo/cookbooks/'
#cookbook_path            ["#{current_dir}/../cookbooks/"]
