log_level                :info
log_location             STDOUT
node_name                'dev'
client_key               '/home/jenkins/workspace/Chef-CookbookUpload/.chef/sasi.pem'
validation_client_name   'sasi'
validation_key           '/home/jenkins/workspace/Chef-CookbookUpload/.chef/atb-chef-admin.pem'
chef_server_url          'https://54.211.154.197/organizations/atb'
syntax_check_cache_path  '/home/jenkins/workspace/Chef-CookbookUpload/.chef/syntax_check_cache'
cookbook_path            '/home/jenkins/workspace/Chef-CookbookUpload/cookbooks/'
#cookbook_path            ["#{current_dir}/../cookbooks/"]
